name: Builder

on:
  workflow_dispatch:

env:
  CMAKE_VERSION: 3.20.2
  LLVM_VERSION: 14.0.0
  NDK_VERSION: r25b

jobs:
  linux_and_android:
    runs-on: ubuntu-latest
    steps:
    - name: checkout master
      uses: actions/checkout@v4

    - name: init linux cross compile env
      run: |
        sh scripts/setup_linux_cross_compile.sh
        mkdir -p artifact
      shell: bash

    - name: compile linux
      run: |
        python3 scripts/platform_builder.py --platform=linux --arch=all --cmake_dir=$HOME/opt/cmake-$CMAKE_VERSION --llvm_dir=$HOME/opt/llvm-$LLVM_VERSION
        cp include/dobby.h build/linux
      shell: bash
    
    - name: compile android
      run: |
        python3 scripts/platform_builder.py --platform=android --arch=all --cmake_dir=$HOME/opt/cmake-$CMAKE_VERSION --llvm_dir=$HOME/opt/llvm-$LLVM_VERSION --android_ndk_dir=$HOME/opt/ndk-$NDK_VERSION
        cp include/dobby.h build/android
      shell: bash
    - name: Upload Build 
      uses: actions/upload-artifact@v4
      with:
        name: build-output
        path: build/

  macos_and_iphoneos:
    runs-on: macos-latest
    steps:
    - name: checkout dev
      uses: actions/checkout@v4

    - name: init macos compile env
      run: |
        sh scripts/setup_macos_cross_compile.sh
        mkdir -p artifact
      shell: bash

    - name: compile macos
      run: |
        python3 scripts/platform_builder.py --platform=macos --arch=all --cmake_dir=$HOME/opt/cmake-$CMAKE_VERSION/CMake.app/Contents
        cp include/dobby.h build/macos
        
      shell: bash
    
    - name: compile iphoneos
      run: |
        python3 scripts/platform_builder.py --platform=iphoneos --arch=all --cmake_dir=$HOME/opt/cmake-$CMAKE_VERSION/CMake.app/Contents
        cp include/dobby.h build/iphoneos
      shell: bash

    - name: Upload Build 
      uses: actions/upload-artifact@v4
      with:
        name: build-output
        path: build/
